---
- name: Converge
  hosts: all
  become: true

  vars:
    ufw_default_incoming_policy: "deny"
    ufw_default_outgoing_policy: "allow"
    ufw_allow_ssh: true
    ufw_ssh_port: "22"
    ufw_rules:
      - rule: allow
        port: "80"
        proto: tcp
        comment: "HTTP"
      - rule: allow
        port: "443"
        proto: tcp
        comment: "HTTPS"

  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: ansible-role-ufw
